# Generated by Django 4.2.4 on 2024-10-09 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disabilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('deleted', 'Deleted'), ('formed', 'Formes'), ('completed', 'Completed'), ('rejected', 'Rejected')], max_length=20)),
                ('data_created', models.DateField()),
                ('data_compilation', models.DateTimeField()),
                ('data_finished', models.DateTimeField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_requests', to=settings.AUTH_USER_MODEL)),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderator_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Disabilities',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Patronage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField()),
                ('img', models.CharField(max_length=80)),
                ('img_background', models.CharField(max_length=80)),
                ('deleted', models.BooleanField()),
            ],
            options={
                'db_table': 'Patronage',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Disabilities_Patronage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('disabilities_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_social_service.disabilities')),
                ('patronage_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_social_service.patronage')),
            ],
            options={
                'db_table': 'Disabilities_Patronage',
                'managed': True,
            },
        ),
    ]
